export type TransactionType = 'receipt' | 'payment'
export type TransactionCategory = 'receipt' | 'adjustment' | 'sales' | 'payment' | 'purchase'
export type UserRole = 'shopkeeper' | 'customer'
export type RecurringInterval =
  | 'daily'
  | 'weekly'
  | 'every_15_days'
  | 'monthly'
  | 'quarterly'
  | 'half_yearly'
  | 'yearly'
export type RecurringTransactionCategory = 'sales' | 'purchase'

export interface AppUser {
  id: string
  name: string
  phone: string
  email?: string | null
  role: UserRole
  createdAt: string
}

export interface Account {
  id: string
  name: string
  phone: string
  email?: string | null
  role: UserRole
  shopAppId: string | null
  phoneVerified: boolean
  createdAt: string
}

export interface Session {
  token: string
  userId: string
  createdAt: string
  expiresAt: number
}

export interface OtpRecord {
  phone: string
  code: string
  purpose: 'login' | 'register'
  expiresAt: number
}

export interface PendingRegistration {
  name: string
  phone: string
  shopName: string
  shopAddress: string
  role: UserRole
  createdAt: string
  expiresAt: number
}

export interface AuthStore {
  accounts: Account[]
  sessions: Session[]
  otps: OtpRecord[]
  pendingRegistrations: PendingRegistration[]
}

export interface Transaction {
  id: string
  type: TransactionType
  category: TransactionCategory
  amount: number
  remarks: string
  userId: string
  userName: string
  customerId: string | null
  customerName: string | null
  customerPhone: string | null
  /** Null for adjustment entries (no cash/bank account). */
  cashAccountId: string | null
  cashAccountName: string | null
  attachmentName: string | null
  attachmentPath: string | null
  /** Set only when this entry was generated by a recurring billing schedule. */
  recurringBillingId: string | null
  recurringOccurrenceDate: string | null
  /** Optional catalog service used for sales / recurring sales. */
  serviceId: string | null
  serviceName: string | null
  createdAt: string
}

export interface ShopService {
  id: string
  name: string
  /** Default bill amount; 0 means user enters amount at sale time. */
  amount: number
  description: string
  createdAt: string
  updatedAt: string
}

export interface ShopTodo {
  id: string
  title: string
  notes: string
  /** call | message | birthday | visit | payment | custom */
  activity: string
  dueDate: string
  /** HH:mm local */
  dueTime: string
  done: boolean
  /** In-app reminders always run on 3d / 1d / due morning. */
  remind3DaysBefore: boolean
  remind1DayBefore: boolean
  remindOnDueMorning: boolean
  /** When true, also offer WhatsApp reminder to admin. */
  whatsappReminder: boolean
  customerId: string | null
  customerName: string | null
  customerPhone: string | null
  reminded3DaysOn: string | null
  reminded1DayOn: string | null
  remindedDueOn: string | null
  createdAt: string
  updatedAt: string
}

export interface RecurringBilling {
  id: string
  customerId: string
  customerName: string
  customerPhone: string
  amount: number
  remarks: string
  serviceId: string | null
  serviceName: string | null
  transactionCategory: RecurringTransactionCategory
  interval: RecurringInterval
  /** First billing period start, YYYY-MM-DD. */
  effectiveDate: string
  /** Period represented by the next bill, YYYY-MM-DD. */
  nextPeriodStartDate: string
  lastPeriodStartDate: string | null
  /** Days after the period ends when the bill is posted. */
  billingDelayDays: number
  /** Next billing/posting date, YYYY-MM-DD. */
  nextRunDate: string
  lastRunDate: string | null
  autoBilling: boolean
  active: boolean
  createdByUserId: string
  createdByName: string
  createdAt: string
  updatedAt: string
}

export type CashAccountKind = 'cash' | 'bank'

export interface CashAccount {
  id: string
  /** Display label in lists (e.g. "HDFC · Savings"). */
  name: string
  kind: CashAccountKind
  bankName?: string | null
  accountName?: string | null
  accountNumber?: string | null
  ifscCode?: string | null
  branch?: string | null
  isSystem: boolean
  openingBalance: number
  createdAt: string
}

export interface DayClose {
  id: string
  date: string
  openingBalance: number
  closingBalance: number
  totalReceipts: number
  totalPayments: number
  transactionCount: number
  closedAt: string
  closedBy: string
}

export interface ShopState {
  appId: string
  shopName: string
  /** Business address printed on invoices. */
  shopAddress: string
  openingBalance: number
  users: AppUser[]
  activeUserId: string | null
  cashAccounts: CashAccount[]
  transactions: Transaction[]
  recurringBillings: RecurringBilling[]
  services: ShopService[]
  todos: ShopTodo[]
  dayCloses: DayClose[]
  setupComplete: boolean
  createdAt: string
}
